import { StyleSheet } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.sm,
    paddingBottom: tokens.spacing.sm,
    backgroundColor: tokens.colors.surfaceCard,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.sm,
    flex: 1,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: tokens.colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleWrap: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 11.5,
    color: tokens.colors.secondary,
    fontWeight: '500',
  },
  refreshButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: tokens.colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    padding: tokens.spacing.md,
    paddingBottom: 40,
    gap: tokens.spacing.md,
  },
  dateNavBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.lg,
    padding: tokens.spacing.sm,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  dateNavBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.md,
    backgroundColor: tokens.colors.surfaceAlt,
    gap: 4,
  },
  dateNavText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  dateCenterBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryFixed,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    gap: 6,
  },
  dateCenterText: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.primary,
  },
  kpiOverviewCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  kpiTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: tokens.spacing.sm,
    gap: 8,
  },
  kpiCardTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: tokens.colors.secondary,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    flexShrink: 1,
  },
  kpiProgressPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
    flexShrink: 0,
  },
  kpiProgressText: {
    fontSize: 11,
    fontWeight: '700',
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: tokens.colors.surfaceAlt,
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: tokens.spacing.md,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  kpiGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceAlt,
    borderRadius: tokens.borderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  kpiGridItem: {
    flex: 1,
    alignItems: 'center',
  },
  kpiGridDivider: {
    width: 1,
    height: 30,
    backgroundColor: tokens.colors.borderSubtle,
  },
  kpiGridLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: tokens.colors.secondary,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  kpiGridValue: {
    fontSize: 15,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    fontVariant: ['tabular-nums'],
  },
  filterSection: {
    gap: tokens.spacing.sm,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.md,
    paddingHorizontal: tokens.spacing.sm,
    height: 40,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: tokens.spacing.xs,
  },
  searchInput: {
    flex: 1,
    height: 40,
    fontSize: 13,
    color: tokens.colors.onBackground,
    paddingVertical: 0,
  },
  filterTabsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  filterTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  filterTabActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  filterTabText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  filterTabTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  sellerCardsList: {
    gap: tokens.spacing.sm,
  },
  sellerCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  sellerCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: tokens.spacing.sm,
    gap: 8,
  },
  sellerProfileLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  avatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: tokens.colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarWrapConfirmed: {
    backgroundColor: '#DCFCE7',
  },
  avatarLetter: {
    fontSize: 15,
    fontWeight: '800',
    color: tokens.colors.secondary,
  },
  avatarLetterConfirmed: {
    color: '#15803D',
  },
  sellerNameWrap: {
    flex: 1,
    minWidth: 0,
  },
  sellerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'nowrap',
  },
  sellerNameText: {
    fontSize: 14,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    flexShrink: 1,
  },
  rolePill: {
    backgroundColor: tokens.colors.surfaceAlt,
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 4,
    flexShrink: 0,
  },
  rolePillText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  departmentText: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  statusBadgeWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
    flexShrink: 0,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  sellerMetricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: tokens.colors.surfaceAlt,
    borderRadius: tokens.borderRadius.md,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: tokens.spacing.sm,
  },
  sellerMetricCol: {
    alignItems: 'center',
  },
  sellerMetricLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
    letterSpacing: 0.4,
    marginBottom: 1,
  },
  sellerMetricVal: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    fontVariant: ['tabular-nums'],
  },
  proofFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
    gap: 8,
  },
  proofMetaLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
    minWidth: 0,
  },
  proofMetaText: {
    fontSize: 11,
    color: tokens.colors.secondary,
    flexShrink: 1,
  },
  viewSlipBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryFixed,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
    flexShrink: 0,
  },
  viewSlipBtnDisabled: {
    backgroundColor: tokens.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  viewSlipBtnText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: tokens.colors.primary,
  },
  viewSlipBtnTextDisabled: {
    color: tokens.colors.secondary,
  },
  loadingContainer: {
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.spacing.sm,
  },
  loadingText: {
    fontSize: 13,
    color: tokens.colors.secondary,
  },
  emptyContainer: {
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.spacing.xs,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  emptySub: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
})
