import { StyleSheet } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: tokens.colors.surfaceContainerLowest,
  },
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  compactToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
    backgroundColor: tokens.colors.surfaceCard,
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.pill,
    paddingHorizontal: 12,
    height: 38,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: tokens.colors.onBackground,
    paddingVertical: 0,
  },
  addIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: tokens.colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    ...tokens.shadows.card,
  },
  filterRow: {
    maxHeight: 50,
    backgroundColor: tokens.colors.surfaceCard,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  filterRowContent: {
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 8,
    gap: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  filterChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  filterChipTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.md,
    paddingBottom: 40,
    flexGrow: 1,
  },
  loadingContainer: {
    padding: 36,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  emptyState: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 8,
    marginTop: 12,
    ...tokens.shadows.card,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  emptyText: {
    fontSize: 12,
    color: tokens.colors.secondary,
    textAlign: 'center',
  },
  invoiceCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  headerTitleCol: {
    flex: 1,
    minWidth: 0,
  },
  invNumRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  invNum: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  orderTag: {
    fontSize: 11,
    color: tokens.colors.secondary,
    fontWeight: '600',
  },
  customerName: {
    fontSize: 13.5,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 9999,
    flexShrink: 0,
  },
  statusText: {
    fontSize: 10,
    fontWeight: '700',
  },
  cardDivider: {
    height: 1,
    backgroundColor: tokens.colors.borderSubtle,
    marginVertical: 10,
  },
  cardMetrics: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metricItem: {
    flex: 1,
  },
  metricLabel: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginBottom: 2,
  },
  metricVal: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  cardActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
  },
  recordPaymentQuickBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: 8,
    paddingVertical: 7,
    gap: 6,
  },
  recordPaymentQuickText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
  printQuickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    gap: 5,
  },
  printQuickBtnText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  detailSheet: {
    backgroundColor: tokens.colors.surfaceCard,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    padding: 16,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  detailTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  detailSubtitle: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  detailBody: {
    paddingVertical: 12,
  },
  infoBox: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    gap: 3,
  },
  boxTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 4,
  },
  boxText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  itemName: {
    fontSize: 13,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  itemSku: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  itemTotal: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  calcBox: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: 12,
    padding: 12,
    marginVertical: 12,
    gap: 6,
  },
  calcRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  calcLabel: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  calcVal: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  calcTotalRow: {
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
    paddingTop: 8,
    marginTop: 4,
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  totalVal: {
    fontSize: 16,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  noPaymentText: {
    fontSize: 12,
    color: tokens.colors.textMuted,
    fontStyle: 'italic',
    marginBottom: 12,
  },
  paymentRecordRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  paymentMethodText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  paymentRefText: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  paymentAmountText: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.statusSuccess,
  },
  paymentDateText: {
    fontSize: 10,
    color: tokens.colors.textMuted,
    marginTop: 1,
  },
  payBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: 12,
    paddingVertical: 12,
    gap: 8,
    marginTop: 16,
    marginBottom: 20,
  },
  payBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
  paidInFullBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E6F4EA',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 8,
    marginTop: 16,
    marginBottom: 20,
  },
  paidInFullText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#15803D',
  },
  payContextBox: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
  },
  payContextLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  payContextBalance: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.statusError,
    marginTop: 2,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 6,
  },
  input: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 13,
    color: tokens.colors.onBackground,
    marginBottom: 12,
  },
  methodSelector: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  methodBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: tokens.colors.surfaceMuted,
    gap: 4,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  methodBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  methodBtnText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  methodBtnTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  submitPayBtn: {
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 20,
  },
  submitPayText: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
  printInvoiceBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: tokens.borderRadius.pill,
    paddingVertical: 12,
  },
  printInvoiceBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
  shareInvoiceBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: tokens.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.pill,
    paddingVertical: 12,
  },
  shareInvoiceBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.primary,
  },
  footer: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    padding: tokens.spacing.md,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
    ...tokens.shadows.actionSheet,
  },
  footerButtonsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  closeFooterButton: {
    flex: 1,
    height: tokens.touchTarget.actionButtonHeight,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.pill,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeFooterButtonText: {
    color: tokens.colors.onBackground,
    fontSize: 13,
    fontWeight: '700',
  },
  itemsSection: {
    marginTop: 14,
    marginBottom: 8,
  },
  itemActionsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
    marginBottom: 10,
  },
  addItemBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 9,
    paddingHorizontal: 8,
    borderRadius: tokens.borderRadius.pill,
  },
  addItemBtnPrimary: {
    backgroundColor: tokens.colors.primaryContainer,
  },
  addItemBtnOutlined: {
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  addItemBtnTonal: {
    backgroundColor: tokens.colors.actionPrimaryBg,
  },
  addItemBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  createItemBox: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  itemBoxTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  itemBoxIndex: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
  },
  itemInput: {
    backgroundColor: tokens.colors.surfaceCard,
    fontSize: 13,
    marginBottom: 6,
  },
  inlineInputs: {
    flexDirection: 'row',
  },
})
