import { StyleSheet } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconBox: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: tokens.colors.primaryContainer + '18',
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    letterSpacing: -0.3,
  },
  screenSubtitle: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  catalogLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: tokens.colors.primaryContainer + '15',
  },
  catalogLinkText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  newPoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: tokens.colors.primaryContainer,
  },
  newPoBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
  searchRow: {
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: tokens.colors.outline,
    paddingHorizontal: 12,
    height: 40,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: tokens.colors.onBackground,
  },
  filterScroll: {
    maxHeight: 38,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: tokens.colors.outline,
  },
  filterChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  filterChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  filterChipTextActive: {
    color: tokens.colors.onPrimary,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
    gap: 10,
  },
  centerBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: 13,
    color: tokens.colors.secondary,
    marginTop: 8,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginTop: 12,
  },
  emptySubtitle: {
    fontSize: 12,
    color: tokens.colors.secondary,
    textAlign: 'center',
    marginTop: 4,
    paddingHorizontal: 32,
  },
  poCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: tokens.colors.outline,
    gap: 10,
  },
  poCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  poIdGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    marginRight: 8,
  },
  poIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: tokens.colors.primaryContainer + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  poNumber: {
    fontSize: 14,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  poSupplierRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
  },
  poSupplier: {
    fontSize: 11,
    color: tokens.colors.secondary,
    fontWeight: '500',
    flexShrink: 1,
  },
  poStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#F1F5F9',
  },
  poStatusBadgeOrdered: {
    backgroundColor: '#FEF3C7',
  },
  poStatusBadgeReceived: {
    backgroundColor: '#D1FAE5',
  },
  poStatusText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748B',
  },
  poStatusTextOrdered: {
    color: '#B45309',
  },
  poStatusTextReceived: {
    color: '#047857',
  },
  poItemSummaryBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    padding: 10,
  },
  poItemSummaryTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  poItemSummaryMeta: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  poCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  poCostLabel: {
    fontSize: 10,
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  poCostValue: {
    fontSize: 15,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
  },
  receiveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: tokens.colors.statusSuccess,
  },
  receiveBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
  viewDetailBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: tokens.colors.primaryContainer + '15',
  },
  viewDetailBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    flexShrink: 1,
    overflow: 'hidden',
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.outline,
    backgroundColor: '#FFFFFF',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  modalSubtitle: {
    fontSize: 12,
    color: tokens.colors.secondary,
    marginTop: 2,
    fontWeight: '500',
  },
  formScroll: {
    flex: 1,
  },
  formScrollContent: {
    padding: 16,
    paddingBottom: 24,
  },
  detailSummaryBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: tokens.colors.outline,
  },
  detailMetricCol: {
    flex: 1,
    alignItems: 'center',
  },
  detailMetricDivider: {
    width: 1,
    height: 28,
    backgroundColor: tokens.colors.outline,
  },
  detailMetricLabel: {
    fontSize: 9.5,
    fontWeight: '800',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  detailMetricVal: {
    fontSize: 13.5,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    marginTop: 2,
  },
  detailExpectedBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    marginBottom: 12,
    gap: 6,
  },
  detailExpectedText: {
    fontSize: 11.5,
    color: '#166534',
    fontWeight: '600',
  },
  detailNotesBox: {
    backgroundColor: '#FFFBEB',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  detailNotesLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#92400E',
  },
  detailNotesText: {
    fontSize: 11.5,
    color: '#78350F',
    marginTop: 2,
  },
  detailItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  detailItemName: {
    fontSize: 12.5,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  detailItemSku: {
    fontSize: 10.5,
    color: tokens.colors.secondary,
    fontFamily: 'monospace',
  },
  detailItemQty: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  detailItemTotal: {
    fontSize: 12.5,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
  },
  receivedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DCFCE7',
    borderRadius: 10,
    paddingVertical: 12,
    gap: 6,
  },
  receivedBannerText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#15803D',
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 6,
    marginTop: 10,
  },
  supChoice: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: tokens.colors.outline,
    backgroundColor: '#F8FAFC',
  },
  supChoiceActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  supChoiceText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  supChoiceTextActive: {
    color: tokens.colors.onPrimary,
  },
  poActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
  },
  poActionBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  lineItemHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  unitSummary: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  emptyItemsBox: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: tokens.colors.outline,
    marginBottom: 12,
  },
  emptyItemsTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginTop: 6,
  },
  emptyItemsSubtitle: {
    fontSize: 11,
    color: tokens.colors.secondary,
    textAlign: 'center',
    marginTop: 2,
  },
  poItemRow: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: tokens.colors.outline,
    padding: 10,
    gap: 8,
  },
  poItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  poItemName: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  poItemSku: {
    fontSize: 10,
    color: tokens.colors.secondary,
    fontFamily: 'monospace',
  },
  poItemControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.outline,
    borderRadius: 6,
  },
  stepperBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  stepperVal: {
    fontSize: 12,
    fontWeight: '700',
    minWidth: 26,
    textAlign: 'center',
    paddingHorizontal: 4,
    paddingVertical: 0,
    includeFontPadding: false,
    color: tokens.colors.onBackground,
  },
  costInputGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  costInputLabel: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  costInput: {
    borderWidth: 1,
    borderColor: tokens.colors.outline,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    width: 60,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
    color: tokens.colors.onBackground,
  },
  itemTotalCost: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: tokens.colors.outline,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 13,
    color: tokens.colors.onBackground,
    marginBottom: 6,
  },
  sheetFooter: {
    paddingHorizontal: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.outline,
  },
  submitPoBtn: {
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  submitPoBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onPrimary,
  },
})
