import { StyleSheet, Platform } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  // Removed: header, title, subtitle, headerActions (replaced by compactHeaderRow)
  compactHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: tokens.spacing.sm,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
    gap: 6,
  },
  stockBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    gap: 3,
    flexShrink: 0,
    ...tokens.shadows.card,
  },
  stockBtnText: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
    fontSize: 11,
  },

  subTabsScroll: {
    flex: 1,
  },
  subTabs: {
    flexDirection: 'row',
    paddingLeft: tokens.spacing.sm,
    paddingRight: tokens.spacing.sm,
    gap: 8,
  },
  subTabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 3,
  },
  subTabBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  subTabBtnText: {
    fontSize: 10,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  subTabBtnTextActive: {
    color: tokens.colors.onPrimary,
  },
  collapsibleCatalogToolbar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    backgroundColor: tokens.colors.background,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  // Compact catalog toolbar: search + chips grouped together
  catalogToolbar: {
    paddingHorizontal: tokens.spacing.md,
    paddingTop: 8,
    paddingBottom: 4,
    gap: 6,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    paddingHorizontal: 10,
    height: 36,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: tokens.colors.onBackground,
  },
  addProdBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: tokens.colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    ...tokens.shadows.card,
  },
  catChipsScroll: {
    flexGrow: 0,
  },
  statusChipsRow: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 2,
    paddingBottom: 6,
  },
  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  statusChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  statusChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  statusChipTextActive: {
    color: tokens.colors.onPrimary,
  },
  catChipsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingBottom: 2,
  },
  catChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    justifyContent: 'center',
  },
  catChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  catChipNeedsBarcode: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FDE68A',
  },
  catChipNeedsBarcodeActive: {
    backgroundColor: '#D97706',
    borderColor: '#D97706',
  },
  catChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
    textAlign: 'center',
    includeFontPadding: false,
  },
  catChipNeedsBarcodeText: {
    color: '#B45309',
    fontWeight: '700',
  },
  catChipTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  list: {
    flex: 1,
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.xs,
  },
  productCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    paddingHorizontal: tokens.spacing.sm,
    paddingVertical: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  productCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  prodIconBox: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: tokens.colors.actionPrimaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  prodThumbnail: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: tokens.colors.surfaceMuted,
  },
  prodName: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  prodMeta: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  stockBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  stockBadgeOk: {
    backgroundColor: '#E6F4EA',
  },
  stockBadgeLow: {
    backgroundColor: '#FFDAD6',
  },
  stockBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  stockTextOk: {
    color: '#15803D',
  },
  stockTextLow: {
    color: '#93000A',
  },
  variantSummaryBox: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  varBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 4,
  },
  varBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#B45309',
  },
  attrPill: {
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  attrPillText: {
    fontSize: 10,
    color: tokens.colors.secondary,
    fontWeight: '600',
  },
  quickScanCtaBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  quickScanCtaText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#D97706',
  },
  barcodeSetPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  barcodeSetText: {
    fontSize: 10,
    fontWeight: '600',
    color: tokens.colors.secondary,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  productCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
  },
  sellPrice: {
    fontSize: 16,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  costPrice: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  editPromptText: {
    fontSize: 11,
    color: tokens.colors.primaryContainer,
    fontWeight: '700',
  },
  movementQuickBar: {
    marginBottom: tokens.spacing.sm,
  },
  quickAdjBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingVertical: 10,
    borderRadius: tokens.borderRadius.pill,
    gap: 6,
    ...tokens.shadows.card,
  },
  quickAdjText: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
    fontSize: 13,
  },
  movementCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.md,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  movementHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  movProductName: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  movMeta: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  movBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  movBadgeGreen: {
    backgroundColor: '#E6F4EA',
  },
  movBadgeRed: {
    backgroundColor: '#FFDAD6',
  },
  movBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  movTextGreen: {
    color: '#15803D',
  },
  movTextRed: {
    color: '#BA1A1A',
  },
  movNotes: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 6,
    fontStyle: 'italic',
  },
  movEmptyContainer: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 60,
    paddingHorizontal: tokens.spacing.lg,
    gap: 10,
  },
  movEmptyTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: tokens.colors.onSurface,
    textAlign: 'center' as const,
  },
  movEmptyText: {
    fontSize: 13,
    color: tokens.colors.secondary,
    textAlign: 'center' as const,
    lineHeight: 19,
  },
  movFooter: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 16,
    gap: 6,
  },
  movFooterText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  // Suppliers & Purchase Orders Modern Styles
  poSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: tokens.spacing.md,
    gap: 8,
    marginVertical: tokens.spacing.xs,
  },
  poSearchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.pill,
    paddingHorizontal: 12,
    height: 38,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  poSearchInput: {
    flex: 1,
    fontSize: 12,
    color: tokens.colors.onBackground,
    paddingVertical: 0,
  },
  poActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 12,
    height: 38,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
    ...tokens.shadows.card,
  },
  poActionBtnText: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
    fontSize: 11,
  },
  poSegmentRow: {
    flexDirection: 'row',
    paddingHorizontal: tokens.spacing.md,
    marginVertical: tokens.spacing.xs,
    gap: 8,
  },
  poSegmentBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 7,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 4,
  },
  poSegmentBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  poSegmentBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  poSegmentBtnTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  emptyPoCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    marginTop: 10,
    gap: 6,
  },
  emptyPoTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  emptyPoSub: {
    fontSize: 11,
    color: tokens.colors.secondary,
    textAlign: 'center',
  },
  emptyCreateBtn: {
    marginTop: 8,
    backgroundColor: tokens.colors.actionPrimaryBg,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.primaryContainer,
  },
  emptyCreateBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  poCardModern: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  poCardModernHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  poIdGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  poIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: tokens.colors.actionPrimaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  poModernNumber: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  poSupplierRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 1,
  },
  poModernSupplier: {
    fontSize: 11,
    color: tokens.colors.secondary,
    fontWeight: '500',
  },
  poModernStatusBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#F1F5F9',
  },
  poStatusBadgeReceived: {
    backgroundColor: '#DCFCE7',
  },
  poStatusBadgeOrdered: {
    backgroundColor: '#FEF3C7',
  },
  poModernStatusText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#64748B',
  },
  poStatusTextReceived: {
    color: '#16A34A',
  },
  poStatusTextOrdered: {
    color: '#B45309',
  },
  poItemSummaryBox: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginVertical: 8,
  },
  poItemSummaryTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  poItemSummaryMeta: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  poCardModernFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  poCostLabel: {
    fontSize: 10,
    color: tokens.colors.textMuted,
  },
  poCostValue: {
    fontSize: 14,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  poCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  poReceiveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  poReceiveBtnText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#16A34A',
  },
  poViewDetailsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  poViewDetailsText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  supCardModern: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  supCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  supAvatar: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: tokens.colors.primaryFixed,
    alignItems: 'center',
    justifyContent: 'center',
  },
  supAvatarText: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onPrimaryContainer,
  },
  supNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  supModernName: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  supContactName: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  leadTimeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFEDD5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: tokens.borderRadius.pill,
    gap: 2,
  },
  leadTimeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#EA580C',
  },
  supInfoRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
  },
  supInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  supInfoText: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  supAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  supAddressText: {
    fontSize: 10,
    color: tokens.colors.textMuted,
    flex: 1,
  },
  supActionRow: {
    marginTop: 10,
  },
  supCreatePoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingVertical: 7,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  supCreatePoBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
  poDetailSupCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceCard,
    padding: 12,
    borderRadius: tokens.borderRadius.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  supAvatarSmall: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: tokens.colors.actionPrimaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  poDetailSupName: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  poDetailSupMeta: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  poItemsTable: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.md,
    padding: 12,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  poItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  poItemName: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  poItemSku: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  poItemCost: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  poSummaryCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.md,
    padding: 12,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    marginTop: 12,
  },
  poSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  poSummaryLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  poSummaryTotal: {
    fontSize: 16,
    fontWeight: '900',
    color: tokens.colors.primaryContainer,
  },
  poDeliveryMeta: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: tokens.colors.surfaceOverlay,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: tokens.colors.background,
    borderTopLeftRadius: tokens.borderRadius.card,
    borderTopRightRadius: tokens.borderRadius.card,
    maxHeight: '92%',
    paddingBottom: tokens.spacing.xl,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: tokens.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  formScroll: {
    padding: tokens.spacing.md,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 6,
    marginTop: 8,
  },
  formSubLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: tokens.colors.secondary,
    marginBottom: 4,
  },
  input: {
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.input,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: tokens.colors.onBackground,
  },
  smallInput: {
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 12,
    color: tokens.colors.onBackground,
  },
  formRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
  },
  typeSelectorRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  typeChoice: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 6,
  },
  typeChoiceActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  typeChoiceText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  typeChoiceTextActive: {
    color: tokens.colors.onPrimary,
  },
  catSelectHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  inlineAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  inlineAddBtnText: {
    fontSize: 11,
    color: tokens.colors.primaryContainer,
    fontWeight: '700',
  },
  categoryPickerRow: {
    marginVertical: 4,
    maxHeight: 36,
  },
  addCategoryChipBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    marginRight: 6,
    gap: 4,
  },
  addCategoryChipBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 11,
    fontWeight: '700',
  },
  catPickChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    marginRight: 6,
  },
  catPickChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  catPickChipText: {
    fontSize: 11,
    color: tokens.colors.secondary,
    fontWeight: '600',
  },
  catPickChipTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  simpleFieldsContainer: {
    backgroundColor: tokens.colors.surfaceCard,
    padding: 12,
    borderRadius: tokens.borderRadius.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    marginTop: 10,
  },
  variableBuilderContainer: {
    backgroundColor: tokens.colors.surfaceCard,
    padding: 12,
    borderRadius: tokens.borderRadius.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    marginTop: 10,
  },
  sectionHeaderInner: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 6,
  },
  attrHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  addAttrBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  addAttrBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 10,
    fontWeight: '700',
  },
  attrHintText: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 4,
    marginBottom: 4,
  },
  quickAttrPillsRow: {
    marginVertical: 4,
    maxHeight: 32,
    marginBottom: 10,
  },
  quickAttrChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    marginRight: 6,
    gap: 3,
  },
  quickAttrChipText: {
    fontSize: 11,
    color: '#0369A1',
    fontWeight: '700',
  },
  compactFieldContainer: {
    marginBottom: 0,
  },
  alignedFormLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 4,
    height: 18,
  },
  alignedTextInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 40,
    fontSize: 13,
    color: tokens.colors.onBackground,
  },
  compactFieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 4,
    height: 16,
  },
  compactTextInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 38,
    fontSize: 12,
    color: tokens.colors.onBackground,
  },
  variantFieldLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#475569',
    marginBottom: 3,
    height: 14,
    textTransform: 'uppercase',
  },
  variantTextInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 8,
    height: 36,
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  scanBarcodeRowBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0284C7',
    paddingHorizontal: 12,
    height: 38,
    borderRadius: 8,
    gap: 4,
  },
  scanBarcodeRowBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  emptyAttrPrompt: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    marginBottom: 8,
  },
  attrCard: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 10,
    borderRadius: 10,
    marginBottom: 8,
  },
  attrCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  attrCardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  valChipsWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  valChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  valChipSelected: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  valChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#334155',
  },
  valChipTextSelected: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  valChipAdd: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.actionPrimaryBg,
    borderWidth: 1,
    borderColor: tokens.colors.primaryFixedDim,
    borderStyle: 'dashed',
    gap: 2,
  },
  valChipAddText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  delAttrBtn: {
    height: 38,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  generateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0284C7',
    paddingVertical: 10,
    borderRadius: tokens.borderRadius.pill,
    marginTop: 6,
    marginBottom: 12,
    gap: 6,
  },
  generateBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  matrixContainer: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
    paddingTop: 8,
  },
  matrixTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 0,
  },
  variantRowCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 10,
    marginBottom: 8,
  },
  variantRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  variantRowName: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    paddingVertical: 8,
  },
  switchLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  submitBtn: {
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: tokens.borderRadius.pill,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
    ...tokens.shadows.card,
  },
  submitBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  headerEditPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  headerEditPillText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  detailCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: tokens.colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overviewFooterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
    gap: 8,
  },
  overviewStockInBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 42,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    gap: 4,
  },
  overviewStockInBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#16A34A',
  },
  overviewStockAdjBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 42,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: '#F0F9FF',
    borderWidth: 1,
    borderColor: '#BAE6FD',
    gap: 4,
  },
  overviewStockAdjBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0284C7',
  },
  overviewEditBtn: {
    flex: 1.3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 42,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.primaryContainer,
    gap: 5,
    ...tokens.shadows.card,
  },
  overviewEditBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  supplierPickerRow: {
    flexDirection: 'column',
    gap: 6,
    marginBottom: 8,
  },
  supChoice: {
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    backgroundColor: tokens.colors.surfaceCard,
  },
  supChoiceActive: {
    borderColor: tokens.colors.primaryContainer,
    backgroundColor: tokens.colors.actionPrimaryBg,
  },
  supChoiceText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  supChoiceTextActive: {
    color: tokens.colors.primaryContainer,
    fontWeight: '700',
  },
  dialogOverlay: {
    flex: 1,
    backgroundColor: tokens.colors.surfaceOverlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  dialogCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: tokens.colors.background,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    ...tokens.shadows.card,
  },
  dialogHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  dialogTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  dialogBtn: {
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: tokens.borderRadius.pill,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 14,
  },
  dialogBtnText: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
    fontSize: 13,
  },
  formPhotoCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.md,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  formPhotoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  formSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  r2Badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.colors.statusSuccess + '18',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  r2BadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: tokens.colors.statusSuccess,
  },
  photoUploadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  photoPreviewWrapper: {
    position: 'relative',
    width: 80,
    height: 80,
    borderRadius: tokens.borderRadius.sm,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  photoPreviewImg: {
    width: '100%',
    height: '100%',
  },
  photoRemoveBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#FEE2E2',
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: tokens.borderRadius.sm,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoPlaceholderText: {
    fontSize: 9.5,
    color: tokens.colors.textMuted,
    marginTop: 2,
  },
  photoBtnCol: {
    flex: 1,
    gap: 8,
  },
  photoPickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: tokens.borderRadius.pill,
  },
  photoPickBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.onSurface,
  },
})
