import { StyleSheet, Platform } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  collapsibleHeaderWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    backgroundColor: tokens.colors.background,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.sm,
    gap: tokens.spacing.sm,
    backgroundColor: tokens.colors.background,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.pill,
    paddingHorizontal: tokens.spacing.md,
    height: 44,
    gap: 8,
    ...tokens.shadows.cardInnerDepth,
  },
  searchInput: {
    flex: 1,
    color: tokens.colors.onBackground,
    fontSize: tokens.typography.body.fontSize,
    paddingVertical: 0,
  },
  categoriesWrapper: {
    paddingVertical: tokens.spacing.xs + 2,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  categoriesList: {
    paddingHorizontal: tokens.spacing.md,
    gap: 8,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  categoryChipActive: {
    backgroundColor: tokens.colors.primaryFixed,
    borderColor: tokens.colors.primaryContainer,
  },
  categoryChipText: {
    color: tokens.colors.secondary,
    fontSize: 12,
    fontWeight: '700',
  },
  categoryChipTextActive: {
    color: tokens.colors.primary,
  },
  gridContainer: {
    flex: 1,
  },
  columnWrapper: {
    justifyContent: 'flex-start',
    paddingHorizontal: tokens.spacing.md,
    gap: tokens.spacing.sm,
  },
  gridContent: {
    paddingTop: tokens.spacing.sm,
    paddingBottom: tokens.spacing.xxl + 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: tokens.spacing.xl,
  },
  loadingText: {
    color: tokens.colors.secondary,
    fontSize: 12,
    marginTop: tokens.spacing.sm,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: tokens.spacing.xl,
  },
  emptyTitle: {
    color: tokens.colors.onBackground,
    fontSize: tokens.typography.headlineMedium.fontSize,
    fontWeight: '700',
    marginTop: tokens.spacing.sm,
  },
  emptySub: {
    color: tokens.colors.secondary,
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  floatingCartBar: {
    position: 'absolute',
    bottom: tokens.spacing.md,
    left: tokens.spacing.md,
    right: tokens.spacing.md,
    zIndex: 50,
  },
  floatingCartInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: tokens.colors.surfaceInverse,
    borderRadius: tokens.borderRadius.pill,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.sm + 2,
    ...tokens.shadows.floatingCart,
  },
  floatingCartLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.sm,
  },
  floatingCountBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: tokens.colors.primaryContainer,
    justifyContent: 'center',
    alignItems: 'center',
  },
  floatingCountText: {
    color: tokens.colors.onPrimary,
    fontSize: 13,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  floatingTotalLabel: {
    color: tokens.colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  floatingTotalValue: {
    color: tokens.colors.surfaceBase,
    fontSize: tokens.typography.priceDisplay.fontSize,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  floatingCheckoutCta: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  floatingCheckoutText: {
    color: tokens.colors.onPrimary,
    fontSize: tokens.typography.bodySemibold.fontSize,
    fontWeight: '700',
  },
  checkoutSheetSafeArea: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  checkoutSheetContainer: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  checkoutSheetHeader: {
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.lg,
    paddingBottom: tokens.spacing.md,
    backgroundColor: tokens.colors.background,
  },
  checkoutSheetHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkoutSheetTitle: {
    color: tokens.colors.onBackground,
    fontSize: tokens.typography.headlineLarge ? tokens.typography.headlineLarge.fontSize : 28,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  checkoutSheetSub: {
    color: tokens.colors.secondary,
    fontSize: 12,
  },
  closeSheetBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: tokens.colors.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartListContainer: {
    flex: 1,
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  stepDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: tokens.colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotActive: {
    backgroundColor: tokens.colors.primaryContainer,
  },
  stepDotText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  stepDotTextActive: {
    color: tokens.colors.onPrimary,
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: tokens.colors.surfaceMuted,
    marginHorizontal: 8,
  },
  stepLineActive: {
    backgroundColor: tokens.colors.primaryContainer,
  },
  stepOneActionContainer: {
    padding: tokens.spacing.md,
    paddingBottom: Platform.OS === 'ios' ? 24 : tokens.spacing.md,
    backgroundColor: 'transparent',
  },
  continueToDetailsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingVertical: 14,
    borderRadius: tokens.borderRadius.pill,
    gap: 8,
  },
  continueToDetailsBtnDisabled: {
    backgroundColor: tokens.colors.textDisabled,
    opacity: 0.6,
  },
  continueToDetailsText: {
    color: tokens.colors.onPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  stepThreeActionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.sm,
    paddingBottom: Platform.OS === 'ios' ? 24 : tokens.spacing.md,
    gap: 10,
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
  },
  stepThreeBackBtn: {
    width: 85,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.surfaceAlt,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 4,
  },
  stepThreeBackText: {
    color: tokens.colors.onBackground,
    fontSize: 14,
    fontWeight: '700',
  },
  stepThreeConfirmBtn: {
    flex: 1,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: tokens.borderRadius.pill,
    paddingHorizontal: 12,
    gap: 6,
    ...tokens.shadows.card,
  },
  stepThreeConfirmText: {
    color: tokens.colors.onPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
})
