import { StyleSheet, Platform } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.sm,
    paddingBottom: tokens.spacing.xs,
    backgroundColor: tokens.colors.background,
  },
  title: {
    fontSize: tokens.typography.headlineLargeMobile.fontSize,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  subtitle: {
    fontSize: tokens.typography.caption.fontSize,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  refreshBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: tokens.colors.surfaceCard,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  roleTabsContainer: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
    backgroundColor: tokens.colors.background,
  },
  roleTabsContent: {
    paddingHorizontal: tokens.spacing.md,
    gap: 8,
    flexDirection: 'row',
  },
  roleTabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 6,
  },
  roleTabBtnActive: {
    backgroundColor: tokens.colors.actionPrimaryBg,
    borderColor: tokens.colors.primaryContainer,
  },
  roleTabIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  roleTabText: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  roleTabTextActive: {
    color: tokens.colors.primaryContainer,
    fontWeight: '700',
  },
  roleCountBadge: {
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 10,
  },
  roleCountBadgeActive: {
    backgroundColor: tokens.colors.primaryContainer,
  },
  roleCountText: {
    fontSize: 10,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  roleCountTextActive: {
    color: tokens.colors.onPrimary,
  },
  content: {
    flex: 1,
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.sm,
  },
  roleSummaryCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  roleSummaryTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  roleSummaryInfo: {
    flex: 1,
  },
  roleSummaryName: {
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  roleSlugBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  roleSlugText: {
    fontSize: 10,
    fontWeight: '700',
  },
  roleSummaryDesc: {
    fontSize: 12,
    color: tokens.colors.secondary,
    marginTop: 4,
    lineHeight: 16,
  },
  lockBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EDE9FE',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
  },
  lockBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#5B21B6',
  },
  superAdminNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#EDE9FE',
    padding: 10,
    borderRadius: tokens.borderRadius.md,
    marginTop: 12,
  },
  superAdminNoticeText: {
    flex: 1,
    fontSize: 11,
    color: '#5B21B6',
    fontWeight: '600',
    lineHeight: 15,
  },
  permissionsStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
  },
  statItem: {
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 10,
    color: tokens.colors.textMuted,
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  statValue: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginTop: 2,
  },
  statDivider: {
    width: 1,
    height: 24,
    backgroundColor: tokens.colors.borderSubtle,
  },
  successBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#E6F4EA',
    padding: 8,
    borderRadius: 8,
    marginTop: 10,
  },
  successBannerText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.statusSuccess,
  },
  moduleGroupCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  moduleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  moduleHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  moduleIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moduleTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  moduleCount: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  bulkToggleBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceMuted,
  },
  bulkToggleText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  accordionChevron: {
    marginLeft: 4,
  },
  moduleDivider: {
    height: 1,
    backgroundColor: tokens.colors.borderSubtle,
    marginVertical: 12,
  },
  permissionsList: {
    gap: 12,
  },
  permissionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  permissionInfo: {
    flex: 1,
  },
  permissionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  permissionName: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  slugCodeChip: {
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  slugCodeText: {
    fontSize: 9,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  originBadgeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 10,
    borderWidth: 1,
  },
  originBadgeText: {
    fontSize: 9,
    fontWeight: '700',
  },
  permissionDesc: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
    lineHeight: 15,
  },
  floatingActionBar: {
    position: 'absolute',
    bottom: 20,
    left: tokens.spacing.md,
    right: tokens.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: tokens.colors.surfaceCard,
    padding: 10,
    borderRadius: tokens.borderRadius.card,
    borderWidth: 1,
    borderColor: tokens.colors.primaryContainer,
    ...tokens.shadows.card,
  },
  resetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceMuted,
    gap: 6,
  },
  resetBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  saveBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.primaryContainer,
    gap: 8,
    ...tokens.shadows.card,
  },
  saveBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
  unauthorizedContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: tokens.spacing.xl,
  },
  unauthorizedBox: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.xl,
    alignItems: 'center',
    width: '100%',
    maxWidth: 360,
    ...tokens.shadows.card,
  },
  unauthorizedIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFDAD6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: tokens.spacing.md,
  },
  unauthorizedTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 8,
  },
  unauthorizedSub: {
    fontSize: 13,
    color: tokens.colors.secondary,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: tokens.spacing.lg,
  },
  backHomeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingVertical: 12,
    paddingHorizontal: tokens.spacing.lg,
    borderRadius: tokens.borderRadius.pill,
    gap: 8,
    width: '100%',
    ...tokens.shadows.card,
  },
  backHomeBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
})
