import { StyleSheet } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  contentContainer: {
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.md,
    paddingBottom: tokens.spacing.xl + 20,
  },
  storeCard: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.lg,
    ...tokens.shadows.cardInnerDepth,
  },
  storeCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.md,
  },
  storeIconBox: {
    width: 48,
    height: 48,
    borderRadius: tokens.borderRadius.thumbnail,
    backgroundColor: tokens.colors.primaryFixed,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storeInfo: {
    flex: 1,
  },
  storeNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  storeName: {
    fontSize: tokens.typography.bodyLarge.fontSize,
    fontWeight: '700',
    color: tokens.colors.onSurface,
    flex: 1,
  },
  storeIdBadge: {
    backgroundColor: tokens.colors.secondaryContainer,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  storeIdText: {
    fontSize: 10,
    fontWeight: '700',
    color: tokens.colors.onSecondaryContainer,
  },
  storeAddress: {
    fontSize: 12,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  terminalStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: tokens.colors.statusSuccess,
    marginRight: 6,
  },
  terminalStatusText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.statusSuccess,
  },
  sectionHeaderRow: {
    marginBottom: tokens.spacing.sm,
    marginTop: tokens.spacing.xs,
  },
  sectionTitle: {
    fontSize: tokens.typography.headlineMedium.fontSize,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    letterSpacing: -0.3,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  diagnosticsCard: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    ...tokens.shadows.cardInnerDepth,
  },
  diagnosticRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: tokens.spacing.xs,
  },
  diagnosticLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: tokens.spacing.sm + 2,
  },
  diagnosticIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  diagSuccess: {
    backgroundColor: tokens.colors.badgeSuccessBg,
  },
  diagWarning: {
    backgroundColor: tokens.colors.statusPendingBg,
  },
  diagError: {
    backgroundColor: tokens.colors.badgeErrorBg,
  },
  diagNeutral: {
    backgroundColor: tokens.colors.surfaceContainer,
  },
  diagnosticLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  diagnosticSub: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  refreshHealthBtn: {
    padding: 8,
  },
  syncNowBtn: {
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
  },
  syncNowBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 11,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: tokens.colors.borderSubtle,
    marginVertical: tokens.spacing.sm,
  },
  accountCard: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.lg,
    gap: tokens.spacing.md,
    ...tokens.shadows.cardInnerDepth,
  },
  accountInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.md,
  },
  accountAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: tokens.colors.actionPrimaryBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  accountName: {
    fontSize: 15,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  accountEmail: {
    fontSize: 12,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  accountRoleBadge: {
    alignSelf: 'flex-start',
    backgroundColor: tokens.colors.actionPrimaryBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: tokens.borderRadius.pill,
    marginTop: 4,
  },
  accountRoleText: {
    fontSize: 10,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
    letterSpacing: 0.5,
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.statusError,
    paddingVertical: 12,
    borderRadius: tokens.borderRadius.pill,
    gap: 8,
    ...tokens.shadows.card,
  },
  logoutBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  // Thermal Printer Styles
  addPrinterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
  },
  addPrinterBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  printerListContainer: {
    marginBottom: tokens.spacing.md,
  },
  deviceCardItem: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.sm,
    ...tokens.shadows.cardInnerDepth,
  },
  deviceCardItemDefault: {
    borderColor: tokens.colors.primaryContainer,
  },
  deviceCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  deviceIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: tokens.colors.surfaceMuted,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deviceNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  deviceItemTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  defaultStationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: tokens.borderRadius.pill,
  },
  defaultStationBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#B45309',
  },
  deviceItemEndpoint: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  deviceMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: tokens.spacing.sm,
  },
  roleBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: tokens.borderRadius.sm,
  },
  roleBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  roleBadgeReceipt: {
    backgroundColor: '#DCFCE7',
  },
  roleBadgeReceiptText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#15803D',
  },
  roleBadgeKitchen: {
    backgroundColor: '#FFEDD5',
  },
  roleBadgeKitchenText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#C2410C',
  },
  paperBadge: {
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: tokens.borderRadius.sm,
  },
  paperBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  cutBadge: {
    backgroundColor: tokens.colors.surfaceAlt,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: tokens.borderRadius.sm,
  },
  cutBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  deviceCardActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: tokens.spacing.sm + 2,
    paddingTop: tokens.spacing.xs + 2,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
  },
  deviceActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  deviceActionBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.primary,
  },
  printerCard: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.lg,
    ...tokens.shadows.cardInnerDepth,
  },
  printerInputLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: tokens.colors.secondary,
    letterSpacing: 0.5,
    marginBottom: 6,
    height: 15,
    lineHeight: 15,
  },
  printerTypeRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: tokens.spacing.sm,
  },
  printerTypeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: tokens.colors.surfaceAlt,
    paddingVertical: 9,
    paddingHorizontal: 8,
    borderRadius: tokens.borderRadius.md,
    borderWidth: 1.5,
    borderColor: tokens.colors.borderSubtle,
  },
  printerTypeChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  printerTypeChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  printerTypeChipTextActive: {
    color: tokens.colors.onPrimary,
  },
  printerFieldsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: tokens.spacing.xs,
  },
  printerTextInput: {
    height: 42,
    backgroundColor: tokens.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.md,
    paddingHorizontal: tokens.spacing.sm + 2,
    fontSize: 13,
    color: tokens.colors.onSurface,
  },
  paperWidthChip: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.surfaceAlt,
    paddingVertical: 9,
    paddingHorizontal: 8,
    borderRadius: tokens.borderRadius.md,
    borderWidth: 1.5,
    borderColor: tokens.colors.borderSubtle,
  },
  paperWidthChipActive: {
    backgroundColor: tokens.colors.primaryFixed,
    borderColor: tokens.colors.primaryContainer,
  },
  paperWidthText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  paperWidthTextActive: {
    color: tokens.colors.primary,
    fontWeight: '800',
  },
  autoCutRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: tokens.spacing.sm,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
    marginTop: tokens.spacing.sm,
  },
  autoCutLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  autoCutSub: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  bluetoothTip: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 4,
    fontStyle: 'italic',
  },
  printerActionButtonsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: tokens.spacing.sm + 2,
  },
  testPrintBtn: {
    flex: 1,
    height: 42,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  testPrintBtnText: {
    color: tokens.colors.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  savePrinterBtn: {
    flex: 1.4,
    height: 42,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.primaryContainer,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    ...tokens.shadows.card,
  },
  savePrinterBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: tokens.spacing.md,
  },
  deviceModalContainer: {
    width: '100%',
    maxWidth: 440,
    maxHeight: '85%',
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.xl,
    padding: tokens.spacing.lg,
    ...tokens.shadows.actionSheet,
  },
  deviceModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: tokens.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  deviceModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  deviceModalSubtitle: {
    fontSize: 12,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  modalCancelBtn: {
    flex: 1,
    height: 42,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCancelBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  modalSaveBtn: {
    flex: 1.3,
    height: 42,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.primaryContainer,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    ...tokens.shadows.card,
  },
  modalSaveBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  brandingLogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.md,
    marginTop: tokens.spacing.xs,
    padding: tokens.spacing.sm + 2,
    backgroundColor: tokens.colors.surfaceAlt,
    borderRadius: tokens.borderRadius.card,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  brandingLogoPreviewBox: {
    width: 60,
    height: 60,
    borderRadius: tokens.borderRadius.md,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  brandingLogoImg: {
    width: 52,
    height: 52,
  },
  logoPickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
  },
  logoPickerBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  logoRemoveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FEE2E2',
    paddingHorizontal: tokens.spacing.sm + 4,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
  },
  logoRemoveBtnText: {
    color: tokens.colors.statusError,
    fontSize: 12,
    fontWeight: '700',
  },
  brandingHelpText: {
    fontSize: 11,
    color: tokens.colors.secondary,
    lineHeight: 15,
  },
  storeLogoBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: tokens.colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    overflow: 'hidden',
  },
  restorePresetsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.colors.surfaceAlt,
    paddingHorizontal: tokens.spacing.sm + 4,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  restorePresetsBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  emptyPrinterCard: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderStyle: 'dashed',
    marginBottom: tokens.spacing.md,
  },
  emptyPrinterIconBox: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: tokens.colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: tokens.spacing.sm,
  },
  emptyPrinterTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 4,
  },
  emptyPrinterSub: {
    fontSize: 12,
    color: tokens.colors.secondary,
    textAlign: 'center',
    lineHeight: 16,
    maxWidth: 280,
  },
  emptyAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
  },
  emptyAddBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  emptyRestoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.colors.surfaceAlt,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  emptyRestoreBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
})
