import { StyleSheet } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  subTabSegmentContainer: {
    flexDirection: 'row',
    backgroundColor: tokens.colors.surfaceCard,
    padding: 4,
    marginHorizontal: tokens.spacing.md,
    marginTop: tokens.spacing.sm,
    marginBottom: 4,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 4,
  },
  subTabSegmentBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 7,
    borderRadius: tokens.borderRadius.pill,
    gap: 5,
  },
  subTabSegmentBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    ...tokens.shadows.card,
  },
  subTabSegmentText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  subTabSegmentTextActive: {
    color: tokens.colors.onPrimary,
  },
  header: {
    paddingVertical: tokens.spacing.sm,
    backgroundColor: tokens.colors.background,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  toolbarScrollContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: tokens.spacing.md,
    gap: 8,
  },
  generateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  generateBtnText: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
    fontSize: 13,
  },
  salaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.primaryContainer,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  salaryBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  salaryBtnText: {
    color: tokens.colors.primaryContainer,
    fontWeight: '600',
    fontSize: 13,
  },
  salaryBtnTextActive: {
    color: tokens.colors.onPrimary,
  },
  salaryCardItem: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.sm,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  salaryCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  salaryInputGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  salaryInput: {
    width: 80,
    textAlign: 'right',
    paddingVertical: 4,
    paddingHorizontal: 6,
    height: 34,
  },
  salarySaveBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: tokens.colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reserveSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
  },
  disburseMiniBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.colors.primaryContainer + '15',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: tokens.borderRadius.pill,
  },
  disburseMiniBtnText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  listContent: {
    padding: tokens.spacing.md,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  empty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  emptyText: {
    color: tokens.colors.secondary,
    marginTop: 12,
  },
  card: {
    backgroundColor: tokens.colors.surfaceCard,
    padding: tokens.spacing.md,
    borderRadius: tokens.borderRadius.md,
    marginBottom: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  cardIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cardIdText: {
    flex: 1,
    minWidth: 0,
  },
  avatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: tokens.colors.primaryContainer + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 15,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
  },
  cardDeleteBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  figuresRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  figureBox: {
    flex: 1,
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.sm,
    paddingHorizontal: 8,
    paddingVertical: 6,
    minWidth: 0,
  },
  figureLabel: {
    fontSize: 9,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    color: tokens.colors.textMuted,
  },
  figureValue: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onSurface,
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  netRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
  },
  netLabel: {
    color: tokens.colors.onSurface,
    fontWeight: '700',
    fontSize: 13,
  },
  netValue: {
    flex: 1,
    textAlign: 'right',
    marginRight: 8,
    color: tokens.colors.primaryContainer,
    fontWeight: '800',
    fontSize: 17,
    fontVariant: ['tabular-nums'],
  },
  periodText: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 10,
    fontWeight: '700',
  },
  userName: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 16,
  },
  modalContent: {
    backgroundColor: tokens.colors.surface,
    borderRadius: tokens.borderRadius.lg,
    padding: tokens.spacing.lg,
  },
  modalTitle: {
    ...tokens.typography.title,
    fontWeight: '700',
    marginBottom: 16,
  },
  modalLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 4,
    marginTop: 6,
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
    backgroundColor: tokens.colors.surfaceCard,
    borderTopLeftRadius: tokens.borderRadius.lg,
    borderTopRightRadius: tokens.borderRadius.lg,
  },
  headerStaffIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  modalStaffName: {
    fontSize: 15,
    fontWeight: '800',
    color: tokens.colors.onSurface,
  },
  headerSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  modalPeriodPill: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  modalCloseIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: tokens.colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  formSectionCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.md,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  infoRowGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  infoColBox: {
    flex: 1,
    backgroundColor: tokens.colors.surfaceMuted,
    padding: 8,
    borderRadius: tokens.borderRadius.sm,
  },
  infoColLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
  },
  infoColValue: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onSurface,
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  twoColGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  inputSubHint: {
    fontSize: 10,
    color: tokens.colors.statusSuccess,
    fontWeight: '600',
    marginTop: 3,
  },
  incentiveAutoInfoBox: {
    backgroundColor: tokens.colors.surfaceMuted,
    padding: 10,
    borderRadius: tokens.borderRadius.sm,
    marginTop: 8,
  },
  incentiveAutoValueText: {
    fontSize: 12,
    color: tokens.colors.onSurface,
  },
  incentiveTierExplanation: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 3,
    lineHeight: 14,
  },
  reserveInfoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: tokens.colors.surfaceMuted,
    padding: 10,
    borderRadius: tokens.borderRadius.sm,
    marginBottom: 10,
  },
  reserveBannerLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
  },
  reserveBannerAmount: {
    fontSize: 16,
    fontWeight: '900',
    color: tokens.colors.statusSuccess,
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  reserveAccruingBadge: {
    backgroundColor: tokens.colors.statusSuccess + '20',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  reserveAccruingText: {
    fontSize: 10,
    fontWeight: '700',
    color: tokens.colors.statusSuccess,
  },
  payoutToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  payoutToggleTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  payoutToggleSub: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  payslipBreakdownCard: {
    backgroundColor: tokens.colors.surfaceMuted,
    padding: 14,
    borderRadius: tokens.borderRadius.md,
    marginTop: 4,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  summaryHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  summaryTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onSurface,
  },
  liveBadge: {
    backgroundColor: tokens.colors.statusSuccess + '20',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  liveBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: tokens.colors.statusSuccess,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 3.5,
  },
  summaryLabel: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  summaryValue: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onSurface,
    fontVariant: ['tabular-nums'],
  },
  netHighlightBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1.5,
    borderTopColor: tokens.colors.borderSubtle,
    backgroundColor: tokens.colors.surfaceCard,
    padding: 10,
    borderRadius: tokens.borderRadius.sm,
  },
  netHighlightLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onSurface,
  },
  netHighlightSub: {
    fontSize: 9.5,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  netHighlightAmount: {
    fontSize: 18,
    fontWeight: '900',
    color: tokens.colors.primaryContainer,
    fontVariant: ['tabular-nums'],
  },
  input: {
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.sm,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13.5,
    color: tokens.colors.onSurface,
    backgroundColor: tokens.colors.surface,
  },
  inputDisabled: {
    backgroundColor: tokens.colors.surfaceMuted,
    color: tokens.colors.secondary,
  },
  pickerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  chipActive: {
    backgroundColor: tokens.colors.primaryContainer + '18',
    borderColor: tokens.colors.primaryContainer,
  },
  chipText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  chipTextActive: {
    color: tokens.colors.primaryContainer,
    fontWeight: '700',
  },
  detailActionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderSubtle,
    backgroundColor: tokens.colors.surfaceCard,
    borderBottomLeftRadius: tokens.borderRadius.lg,
    borderBottomRightRadius: tokens.borderRadius.lg,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 20,
  },
  modalBtnCancel: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: tokens.borderRadius.pill,
  },
  modalBtnCancelText: {
    color: tokens.colors.secondary,
    fontWeight: '600',
  },
  modalBtnDestructive: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FECACA',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: tokens.borderRadius.pill,
    minWidth: 80,
  },
  modalBtnDestructiveText: {
    color: '#DC2626',
    fontWeight: '700',
    fontSize: 12.5,
  },
  modalBtnSecondary: {
    backgroundColor: tokens.colors.surfaceMuted,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: tokens.borderRadius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  modalBtnSecondaryText: {
    color: tokens.colors.primaryContainer,
    fontWeight: '700',
    fontSize: 12.5,
  },
  modalBtnAction: {
    backgroundColor: tokens.colors.primaryContainer,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: tokens.borderRadius.pill,
    minWidth: 90,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  modalBtnActionText: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
    fontSize: 12.5,
  },
  modalBtnPaid: {
    backgroundColor: tokens.colors.statusSuccess,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: tokens.borderRadius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  modalBtnPaidText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 12.5,
  },
  modalBtnFlex: {
    flex: 1,
    minWidth: 0,
  },
  modalBtnDisabled: {
    opacity: 0.5,
  },
  filterSection: {
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.sm,
    gap: 6,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: tokens.spacing.md,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  filterChipActive: {
    backgroundColor: tokens.colors.actionPrimaryBg,
    borderColor: tokens.colors.primaryContainer,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  filterChipTextActive: {
    color: tokens.colors.primaryContainer,
    fontWeight: '700',
  },
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: tokens.borderRadius.sm,
    marginBottom: 12,
  },
  statusBannerText: {
    flex: 1,
    fontSize: 11.5,
    fontWeight: '600',
  },
  cardSelected: {
    borderColor: tokens.colors.primaryContainer,
    borderWidth: 2,
  },
  selectCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: tokens.colors.outline,
    marginLeft: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectCircleOn: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  selectCircleDisabled: {
    opacity: 0.35,
  },
  cardDisabled: {
    opacity: 0.45,
  },
  bulkBar: {
    position: 'absolute',
    bottom: 16,
    left: tokens.spacing.md,
    right: tokens.spacing.md,
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.md,
    borderWidth: 1,
    borderColor: tokens.colors.primaryContainer,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    ...tokens.shadows.card,
  },
  bulkHint: {
    flex: 1,
    fontSize: 12,
    color: tokens.colors.onSurface,
    marginRight: 8,
  },
  bulkPayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: tokens.colors.statusSuccess,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: tokens.borderRadius.pill,
  },
  bulkPayText: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
    fontSize: 13,
  },
  alreadyGeneratedWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: tokens.colors.statusWarning + '18',
    padding: 10,
    borderRadius: tokens.borderRadius.sm,
    marginTop: 12,
  },
  alreadyGeneratedText: {
    flex: 1,
    fontSize: 11.5,
    fontWeight: '600',
    color: tokens.colors.statusWarning,
  },
  // Benefits & Allowances 2x2 Grid Styles
  benefitsGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  benefitInputCol: {
    flex: 1,
  },
  benefitLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 22,
    marginBottom: 4,
  },
  benefitLabelText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  currencyInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.sm,
    backgroundColor: tokens.colors.surface,
    paddingHorizontal: 10,
    height: 42,
  },
  currencyPrefix: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.secondary,
    marginRight: 4,
  },
  benefitTextInput: {
    flex: 1,
    fontSize: 13.5,
    fontWeight: '600',
    color: tokens.colors.onSurface,
    padding: 0,
  },
  // Staff Salary Live Metrics Styles
  salaryMetricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.sm,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginTop: 8,
    marginBottom: 4,
  },
  salaryMetricCol: {
    flex: 1,
  },
  salaryMetricDivider: {
    width: 1,
    height: 24,
    backgroundColor: tokens.colors.borderSubtle,
    marginHorizontal: 8,
  },
  salaryMetricLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
  },
  salaryMetricValue: {
    fontSize: 12,
    fontWeight: '800',
    color: tokens.colors.onSurface,
    marginTop: 1,
  },
  // Batch & Multi-Select Generation Styles
  genTabContainer: {
    flexDirection: 'row',
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.pill,
    padding: 3,
    marginBottom: 14,
  },
  genTabBtn: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: tokens.borderRadius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  genTabBtnActive: {
    backgroundColor: tokens.colors.surfaceCard,
    ...tokens.shadows.card,
  },
  genTabText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  genTabTextActive: {
    color: tokens.colors.primaryContainer,
    fontWeight: '800',
  },
  batchStatsCard: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.md,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  batchStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  batchStatCol: {
    alignItems: 'center',
  },
  batchStatNum: {
    fontSize: 18,
    fontWeight: '900',
    color: tokens.colors.onSurface,
  },
  batchStatLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: tokens.colors.secondary,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  batchStatDivider: {
    width: 1,
    height: 28,
    backgroundColor: tokens.colors.borderSubtle,
  },
  multiStaffList: {
    maxHeight: 220,
    marginBottom: 12,
  },
  multiStaffRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: tokens.borderRadius.sm,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    backgroundColor: tokens.colors.surfaceCard,
    marginBottom: 6,
  },
  multiStaffRowChecked: {
    borderColor: tokens.colors.primaryContainer,
    backgroundColor: tokens.colors.actionPrimaryBg,
  },
  multiStaffRowDisabled: {
    opacity: 0.55,
    backgroundColor: tokens.colors.surfaceMuted,
  },
  checkboxSquare: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: tokens.colors.outline,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxSquareChecked: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  checkboxSquareDisabled: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderColor: tokens.colors.outline,
  },
  multiToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  multiToolbarText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  quickActionText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
})
