import { StyleSheet } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.sm,
  },
  title: {
    fontSize: tokens.typography.headlineLargeMobile.fontSize,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  subtitle: {
    fontSize: tokens.typography.caption.fontSize,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  exportTopBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
    ...tokens.shadows.card,
  },
  exportTopText: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
    fontSize: 12,
  },
  dateSelector: {
    flexDirection: 'row',
    paddingHorizontal: tokens.spacing.md,
    marginVertical: tokens.spacing.xs,
    gap: 6,
  },
  dateSelectorContent: {
    paddingHorizontal: tokens.spacing.sm,
    paddingVertical: 6,
    gap: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  dateBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  dateBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.secondary,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  dateBtnTextActive: {
    color: tokens.colors.onPrimary,
  },
  content: {
    flex: 1,
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.xs,
  },
  // Hero Financial Performance Card
  heroCard: {
    backgroundColor: '#1E293B',
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  heroSubtitle: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94A3B8',
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  heroAmount: {
    fontSize: 28,
    fontWeight: '900',
    color: '#F8FAFC',
    letterSpacing: -0.8,
  },
  heroTrendBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    gap: 3,
  },
  heroTrendText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#22C55E',
  },
  heroBreakdownRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 2,
  },
  heroPillItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  heroPillText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#E2E8F0',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: tokens.spacing.sm,
  },
  gridCard: {
    flex: 1,
    minWidth: '47%',
    backgroundColor: tokens.colors.surfaceCard,
    padding: 12,
    borderRadius: tokens.borderRadius.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  gridLabel: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  gridVal: {
    fontSize: 16,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    marginTop: 4,
  },
  chartCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    marginBottom: tokens.spacing.sm,
    ...tokens.shadows.card,
  },
  chartTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 16,
  },
  chartBarsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    height: 120,
  },
  barColumn: {
    alignItems: 'center',
    width: 45,
    marginHorizontal: 4,
  },
  barValText: {
    fontSize: 9,
    color: tokens.colors.secondary,
    marginBottom: 4,
  },
  barTrack: {
    width: 24,
    height: 80,
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: 6,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  barFill: {
    width: '100%',
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: 6,
  },
  barLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: tokens.colors.secondary,
    marginTop: 6,
  },
  topProductsCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    marginBottom: tokens.spacing.sm,
    ...tokens.shadows.card,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 10,
  },
  productRankRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  rankBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: tokens.colors.actionPrimaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankNum: {
    fontSize: 11,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
  },
  rankName: {
    fontSize: 13,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  rankSales: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  rankRevenue: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  exportSection: {
    gap: 8,
    marginBottom: 40,
    marginTop: 6,
  },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.surfaceCard,
    paddingVertical: 12,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 6,
  },
  exportBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  // Staff Performance Section
  staffSection: {
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  staffHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  staffSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 2,
  },
  staffSectionSub: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  staffPeriodRow: {
    flexDirection: 'row',
    gap: 4,
  },
  staffPeriodBtn: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  staffPeriodBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  staffPeriodText: {
    fontSize: 10,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  staffPeriodTextActive: {
    color: tokens.colors.onPrimary,
  },
  staffCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: tokens.borderRadius.md,
    marginBottom: 6,
    backgroundColor: tokens.colors.background,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 10,
  },
  staffCardTop: {
    borderColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
  },
  staffRankBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: tokens.colors.surfaceContainerLowest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  staffRankBadgeTop: {
    backgroundColor: '#FEF3C7',
  },
  staffRankText: {
    fontSize: 10,
    fontWeight: '800',
    color: tokens.colors.secondary,
  },
  staffInfo: {
    flex: 1,
  },
  staffName: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  staffRole: {
    fontSize: 10,
    fontWeight: '500',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  staffStats: {
    alignItems: 'flex-end',
  },
  staffRevenue: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  staffMeta: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  staffEmpty: {
    alignItems: 'center',
    paddingVertical: 20,
    gap: 8,
  },
  staffEmptyText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  // Filter Banner
  activeFilterBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceContainerLowest,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    marginBottom: tokens.spacing.sm,
    gap: 6,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  activeFilterBannerText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    padding: tokens.spacing.md,
  },
  modalCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    ...tokens.shadows.card,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  modalSubtitle: {
    fontSize: 12,
    color: tokens.colors.secondary,
    marginBottom: 12,
  },
  quickPresetsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  presetChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  presetChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  presetChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  presetChipTextActive: {
    color: tokens.colors.onPrimary,
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
    marginBottom: 4,
  },
  textInput: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.sm,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: tokens.colors.onBackground,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 16,
  },
  modalCancelBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
  },
  modalCancelBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  modalApplyBtn: {
    backgroundColor: tokens.colors.primaryContainer,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
  },
  modalApplyBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },
})
