import { StyleSheet } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  myShiftCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  myShiftHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  myShiftTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  myShiftIconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: tokens.colors.actionPrimaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  myShiftGreeting: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  myShiftSubtitle: {
    fontSize: 10.5,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  myShiftBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: tokens.colors.actionPrimaryBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
  },
  myShiftBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
  },
  perfPeriodRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 10,
  },
  perfPeriodChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  perfPeriodChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  perfPeriodChipText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  perfPeriodChipTextActive: {
    color: '#FFFFFF',
  },
  myShiftMetricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  myShiftMetricCol: {
    flex: 1,
    alignItems: 'center',
  },
  myShiftMetricLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
    marginBottom: 3,
  },
  myShiftMetricValue: {
    fontSize: 14,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  myShiftMetricDivider: {
    width: 1,
    height: 24,
    backgroundColor: tokens.colors.borderSubtle,
  },
  fullTouchWrap: {
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  contentContainer: {
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.sm,
    paddingBottom: 40,
  },
  lowStockBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF1F2',
    borderWidth: 1,
    borderColor: '#FECDD3',
    borderRadius: tokens.borderRadius.card,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 12,
  },
  lowStockBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  lowStockBannerIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFE4E6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lowStockBannerText: {
    fontSize: 12,
    color: '#881337',
    flex: 1,
  },
  lowStockBannerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#FFE4E6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
  },
  lowStockBannerBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#E11D48',
  },
  targetModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: tokens.spacing.md,
  },
  targetModalContent: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 16,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.cardElevated,
  },
  targetModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  targetModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  targetModalSub: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  targetPresetLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: tokens.colors.secondary,
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  targetPresetsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  targetPresetChip: {
    flex: 1,
    paddingVertical: 8,
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.pill,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  targetPresetChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  targetPresetText: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  targetPresetTextActive: {
    color: tokens.colors.onPrimary,
  },
  targetInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.input,
    paddingHorizontal: 12,
    marginTop: 4,
    marginBottom: 14,
  },
  targetDollarSign: {
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.secondary,
    marginRight: 6,
  },
  targetInputField: {
    flex: 1,
    height: 42,
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  targetSaveBtn: {
    backgroundColor: tokens.colors.primaryContainer,
    paddingVertical: 12,
    borderRadius: tokens.borderRadius.pill,
    alignItems: 'center',
  },
  targetSaveBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  // Hero Financial Performance Card
  heroCard: {
    backgroundColor: '#1E293B',
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  heroSubtitle: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94A3B8',
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  heroAmount: {
    fontSize: 28,
    fontWeight: '900',
    color: '#F8FAFC',
    letterSpacing: -0.8,
  },
  heroTrendBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    gap: 3,
  },
  heroTrendText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#22C55E',
  },
  targetSection: {
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  targetLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  targetLabel: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '500',
  },
  targetPercent: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FB923C',
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: 3,
  },
  heroBreakdownRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 2,
  },
  heroPillItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  heroPillText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#E2E8F0',
  },
  // Metric Row
  metricRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  metricCard: {
    flex: 1,
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 10,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  metricCardWarning: {
    backgroundColor: '#FFF5F5',
    borderColor: '#FFD1D1',
  },
  metricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  metricIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: tokens.colors.secondary,
    letterSpacing: 0.5,
  },
  metricLabelWarning: {
    fontSize: 9,
    fontWeight: '700',
    color: '#BA1A1A',
    letterSpacing: 0.5,
  },
  metricValue: {
    fontSize: 16,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  metricValueWarning: {
    fontSize: 16,
    fontWeight: '800',
    color: '#BA1A1A',
  },
  metricMeta: {
    fontSize: 9,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  metricActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginTop: 2,
  },
  metricActionText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#BA1A1A',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    letterSpacing: -0.2,
  },
  sectionSubtitle: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  actionGridContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    height: 128,
  },
  actionCardPrimaryHero: {
    flex: 1.15,
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: 20,
    height: 128,
    overflow: 'hidden',
    ...tokens.shadows.cardElevated,
  },
  actionCardPrimaryHeroTouch: {
    flex: 1,
    padding: 13,
    justifyContent: 'space-between',
  },
  actionCardPrimaryTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  actionIconWrapPrimary: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionPrimaryLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: tokens.borderRadius.pill,
    gap: 4,
  },
  actionPrimaryLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#86EFAC',
  },
  actionPrimaryLiveText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  actionCardPrimaryBottom: {
    marginTop: 6,
  },
  actionTitlePrimary: {
    fontSize: 14,
    fontWeight: '800',
    color: tokens.colors.onPrimary,
    letterSpacing: -0.2,
  },
  actionSubPrimary: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.88)',
    marginTop: 1,
    fontWeight: '500',
  },
  actionPrimaryArrowCircle: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    ...tokens.shadows.card,
  },
  actionSecondaryColumn: {
    flex: 1.35,
    height: 128,
    justifyContent: 'space-between',
    gap: 8,
  },
  actionCardSecondary: {
    height: 60,
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    overflow: 'hidden',
    ...tokens.shadows.card,
  },
  actionCardSecondaryTouch: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 10,
  },
  actionIconWrapSecondary: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionSecondaryInfo: {
    flex: 1,
  },
  actionTitleSecondary: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  actionSubSecondary: {
    fontSize: 10,
    color: tokens.colors.secondary,
    marginTop: 1,
  },
  modulesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  moduleCard: {
    width: '23%',
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  moduleIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  moduleTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    textAlign: 'center',
  },
  moduleSub: {
    fontSize: 8,
    color: tokens.colors.secondary,
    textAlign: 'center',
    marginTop: 1,
  },
  viewAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  viewAllText: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
  },
  filterPillsRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 10,
  },
  filterPill: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  filterPillActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  filterPillText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  filterPillTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  transactionsContainer: {
    marginTop: 2,
  },
  orderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 12,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  orderCardPending: {
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },
  orderCardCancelled: {
    borderLeftWidth: 4,
    borderLeftColor: '#EF4444',
    opacity: 0.85,
  },
  payIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  orderMiddle: {
    flex: 1,
    paddingRight: 8,
  },
  orderTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  orderIdText: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  statusBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 4,
  },
  statusBadgeSuccess: {
    backgroundColor: '#DCFCE7',
  },
  statusBadgePending: {
    backgroundColor: '#FEF3C7',
  },
  statusBadgeCancelled: {
    backgroundColor: '#FEE2E2',
  },
  statusBadgeText: {
    fontSize: 8,
    fontWeight: '800',
  },
  statusTextSuccess: {
    color: '#16A34A',
  },
  statusTextPending: {
    color: '#B45309',
  },
  statusTextCancelled: {
    color: '#DC2626',
  },
  customerName: {
    fontSize: 11,
    color: tokens.colors.onBackground,
    fontWeight: '600',
    marginTop: 2,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
  },
  timeText: {
    fontSize: 10,
    color: tokens.colors.secondary,
  },
  channelText: {
    fontSize: 10,
    color: tokens.colors.textMuted,
  },
  orderRight: {
    alignItems: 'flex-end',
  },
  orderPrice: {
    fontSize: 15,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  payMethodBadge: {
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 3,
  },
  payMethodBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  stateContainer: {
    padding: 24,
    alignItems: 'center',
    gap: 8,
  },
  stateText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  emptyContainer: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 4,
  },
  emptyTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  emptySub: {
    fontSize: 11,
    color: tokens.colors.secondary,
    textAlign: 'center',
  },
})
