import { StyleSheet, Platform } from 'react-native'
import { tokens } from '../../theme/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.background,
  },
  compactHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: tokens.spacing.sm,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
    gap: 6,
  },
  subTabs: {
    flex: 1,
    flexDirection: 'row',
    paddingLeft: tokens.spacing.sm,
    gap: 5,
  },
  subTabBtn: {
    flex: 1,
    paddingVertical: 6,
    alignItems: 'center',
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  subTabBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  subTabText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  subTabTextActive: {
    color: tokens.colors.onPrimary,
  },
  addIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: tokens.colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginRight: 2,
  },
  content: {
    flex: 1,
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.xs,
  },

  /* Audit Log Infinite Scroll & Filter Styles */
  scrollArea: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.sm,
    paddingBottom: tokens.spacing.xl + 40,
  },
  auditSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    paddingHorizontal: 12,
    height: 38,
    marginBottom: 8,
  },
  auditSearchInput: {
    flex: 1,
    fontSize: 13,
    color: tokens.colors.onBackground,
    paddingVertical: 0,
  },
  dateBarRow: {
    maxHeight: 38,
    marginBottom: 6,
  },
  dateBarContent: {
    gap: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateBtn: {
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  dateBtnText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  dateBtnTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  statusChipsRow: {
    maxHeight: 44,
    marginBottom: 8,
  },
  statusChipsContent: {
    gap: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 5,
  },
  statusFilterChipActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  statusFilterChipText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  statusFilterChipTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  countBadge: {
    backgroundColor: 'rgba(0, 0, 0, 0.06)',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 9999,
  },
  countBadgeActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  countBadgeText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  countBadgeTextActive: {
    color: tokens.colors.onPrimary,
  },
  activeFilterBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.actionPrimaryBg,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: tokens.borderRadius.md,
    marginBottom: tokens.spacing.sm,
    gap: 6,
    borderWidth: 1,
    borderColor: tokens.colors.primaryFixedDim,
  },
  activeFilterBannerText: {
    flex: 1,
    fontSize: 11.5,
    color: tokens.colors.primary,
    fontWeight: '600',
  },
  activeFilterHighlight: {
    fontWeight: '700',
    color: tokens.colors.primary,
  },
  summaryBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  summaryDivider: {
    width: 1,
    height: 24,
    backgroundColor: tokens.colors.borderSubtle,
  },
  listSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  listSectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  listSectionSub: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },

  /* Audit Card Styles */
  auditCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.sm,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  auditCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  auditCardIconBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  auditActionBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  auditActionBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  auditTimeText: {
    fontSize: 10,
    color: tokens.colors.textMuted,
  },
  auditTargetText: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginTop: 4,
  },
  auditPillsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  auditDevicePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  auditDevicePillText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#3730A3',
  },
  auditIpPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F0F9FF',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#BAE6FD',
  },
  auditIpPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0369A1',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  auditCardDivider: {
    height: 1,
    backgroundColor: tokens.colors.borderSubtle,
    marginVertical: 8,
  },
  auditCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  auditActorText: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  auditDetailsText: {
    fontSize: 11,
    color: tokens.colors.textMuted,
    flex: 1,
    textAlign: 'right',
  },

  centerLoading: {
    padding: 36,
    alignItems: 'center',
    gap: 8,
  },
  centerLoadingText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  loadingMoreRow: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  loadingMoreText: {
    fontSize: 12,
    color: tokens.colors.secondary,
  },
  emptyCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    gap: 8,
    marginTop: 10,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  emptySub: {
    fontSize: 11,
    color: tokens.colors.secondary,
    textAlign: 'center',
    lineHeight: 16,
  },

  /* User Card Styles */
  userCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: 14,
    marginBottom: tokens.spacing.sm,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    ...tokens.shadows.card,
  },
  userCardInactive: {
    opacity: 0.72,
    backgroundColor: tokens.colors.surfaceMuted,
  },
  userCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarBox: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: tokens.colors.actionPrimaryBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: tokens.colors.primaryContainer,
  },
  avatarBoxInactive: {
    borderColor: tokens.colors.borderSubtle,
    backgroundColor: tokens.colors.surfaceMuted,
  },
  avatarLetter: {
    fontSize: 18,
    fontWeight: '900',
    color: tokens.colors.primaryContainer,
  },
  userName: {
    fontSize: 15,
    fontWeight: '800',
    color: tokens.colors.onBackground,
    flex: 1,
  },
  inactiveBadge: {
    backgroundColor: '#FFDAD6',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  inactiveText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#93000A',
  },
  userEmail: {
    fontSize: 11.5,
    color: tokens.colors.secondary,
    marginTop: 2,
  },
  staffMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
  },
  deptBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 6,
  },
  deptBadgeText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  statusDotPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: tokens.borderRadius.pill,
  },
  statusDotSmall: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusDotText: {
    fontSize: 10,
    fontWeight: '800',
  },
  roleBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  roleBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  userCardDivider: {
    height: 1,
    backgroundColor: tokens.colors.borderSubtle,
    marginVertical: 10,
  },
  userCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statsPreviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: tokens.colors.actionPrimaryBg,
    paddingHorizontal: 10,
    paddingVertical: 5.5,
    borderRadius: tokens.borderRadius.pill,
    borderWidth: 1,
    borderColor: tokens.colors.primaryContainer,
  },
  statsPreviewBtnText: {
    fontSize: 11.5,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
  },
  cardActionIconBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: tokens.colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  reactivateIconBtn: {
    backgroundColor: '#DCFCE7',
    borderColor: '#86EFAC',
  },
  deleteIconBtn: {
    backgroundColor: '#FEE2E2',
    borderColor: '#FCA5A5',
  },
  resetIconBtn: {
    backgroundColor: '#FEF3C7',
    borderColor: '#FDE68A',
  },

  /* ── Reset Password Modal Styles ── */
  resetPwdIconBox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetPwdUserChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: 10,
    padding: 10,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  resetPwdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  resetPwdInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 13,
    fontFamily: 'monospace',
    color: tokens.colors.onBackground,
    backgroundColor: tokens.colors.surface,
  },
  resetPwdActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: tokens.colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    flexShrink: 0,
  },
  resetPwdWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#FEF3C7',
    borderColor: '#FDE68A',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  resetPwdWarningText: {
    flex: 1,
    fontSize: 12,
    color: '#92400E',
    lineHeight: 17,
  },
  resetPwdError: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FEE2E2',
    borderRadius: 8,
    padding: 8,
    marginBottom: 10,
  },
  resetPwdErrorText: {
    flex: 1,
    fontSize: 12,
    color: tokens.colors.statusError,
  },
  resetPwdFooter: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  resetPwdCancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.surface,
  },
  resetPwdCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  resetPwdConfirmBtn: {
    flex: 2,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#D97706',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  resetPwdConfirmText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },


  roleManageBanner: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.md,
    borderWidth: 1,
    borderColor: tokens.colors.primaryContainer,
    ...tokens.shadows.card,
  },
  roleManageBannerContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 12,
  },
  roleManageIconBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: tokens.colors.actionPrimaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roleManageTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  roleManageSub: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 2,
    lineHeight: 15,
  },
  configureRolesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: tokens.borderRadius.pill,
    gap: 6,
    ...tokens.shadows.card,
  },
  configureRolesBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  sectionHeader: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 10,
  },
  groupCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.md,
    marginBottom: tokens.spacing.sm,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  groupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  groupTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  groupUsersCount: {
    fontSize: 11,
    color: tokens.colors.secondary,
  },
  groupDesc: {
    fontSize: 11,
    color: tokens.colors.secondary,
    marginTop: 4,
    marginBottom: 8,
  },
  permList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  permChip: {
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  permChipText: {
    fontSize: 10,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },

  /* Modals */
  modalOverlay: {
    flex: 1,
    backgroundColor: tokens.colors.surfaceOverlay,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: tokens.colors.background,
    borderTopLeftRadius: tokens.borderRadius.card,
    borderTopRightRadius: tokens.borderRadius.card,
    maxHeight: '90%',
    paddingBottom: tokens.spacing.xl,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: tokens.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  formScroll: {
    padding: tokens.spacing.md,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 6,
    marginTop: 8,
  },
  rolePickerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  rolePickBtn: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  rolePickBtnActive: {
    backgroundColor: tokens.colors.primaryContainer,
    borderColor: tokens.colors.primaryContainer,
  },
  rolePickText: {
    fontSize: 11,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  rolePickTextActive: {
    color: tokens.colors.onPrimary,
    fontWeight: '700',
  },
  formSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.borderSubtle,
    marginBottom: 8,
  },
  formSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  formAccrualPreview: {
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.md,
    padding: 12,
    marginTop: 10,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  formAccrualHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 8,
  },
  formAccrualTitle: {
    fontSize: 11.5,
    fontWeight: '700',
    color: tokens.colors.onSurface,
  },
  formAccrualRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  formAccrualLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
  },
  formAccrualValue: {
    fontSize: 13,
    fontWeight: '800',
    color: tokens.colors.onSurface,
    marginTop: 2,
  },
  formAccrualDivider: {
    width: 1,
    height: 24,
    backgroundColor: tokens.colors.borderSubtle,
    marginHorizontal: 10,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 4,
    paddingVertical: 8,
  },
  switchLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: tokens.colors.onBackground,
  },
  submitBtn: {
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: tokens.borderRadius.pill,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
    ...tokens.shadows.card,
  },
  submitBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 14,
    fontWeight: '700',
  },

  /* Calendar Modal Styles */
  customDateModalSheet: {
    backgroundColor: tokens.colors.surfaceCard,
    borderTopLeftRadius: tokens.borderRadius.card,
    borderTopRightRadius: tokens.borderRadius.card,
    paddingHorizontal: tokens.spacing.md,
    paddingTop: tokens.spacing.md,
    paddingBottom: tokens.spacing.xl + 20,
    maxHeight: '92%',
  },
  modalTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  customDateModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  closeModalBtn: {
    padding: 4,
  },
  modeTabs: {
    flexDirection: 'row',
    backgroundColor: tokens.colors.surfaceMuted,
    borderRadius: tokens.borderRadius.pill,
    padding: 3,
    marginBottom: 12,
  },
  modeTab: {
    flex: 1,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: tokens.borderRadius.pill,
  },
  modeTabActive: {
    backgroundColor: tokens.colors.surfaceCard,
    ...tokens.shadows.card,
  },
  modeTabText: {
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
  modeTabTextActive: {
    color: tokens.colors.onBackground,
    fontWeight: '700',
  },
  rangeDisplayRow: {
    marginBottom: 12,
  },
  rangeBadge: {
    backgroundColor: tokens.colors.surfaceMuted,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: tokens.borderRadius.md,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
  },
  rangeBadgeLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: tokens.colors.secondary,
    letterSpacing: 0.5,
  },
  rangeBadgeVal: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.primaryContainer,
    marginTop: 2,
  },
  calendarStyle: {
    borderRadius: tokens.borderRadius.md,
    marginBottom: 16,
  },
  modalActionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  resetModalBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetModalBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.secondary,
  },
  applyModalBtn: {
    flex: 2,
    paddingVertical: 12,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    ...tokens.shadows.card,
  },
  applyModalBtnDisabled: {
    opacity: 0.4,
  },
  applyModalBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onPrimary,
  },

  /* Unauthorized */
  unauthorizedContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: tokens.spacing.xl,
  },
  unauthorizedBox: {
    backgroundColor: tokens.colors.surfaceContainerLowest,
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.xl,
    alignItems: 'center',
    width: '100%',
    maxWidth: 360,
    ...tokens.shadows.card,
  },
  unauthorizedIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFDAD6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: tokens.spacing.md,
  },
  unauthorizedTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: tokens.colors.onBackground,
    marginBottom: 8,
  },
  unauthorizedSub: {
    fontSize: 13,
    color: tokens.colors.secondary,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: tokens.spacing.lg,
  },
  backHomeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    paddingVertical: 12,
    paddingHorizontal: tokens.spacing.lg,
    borderRadius: tokens.borderRadius.pill,
    gap: 8,
    width: '100%',
    ...tokens.shadows.card,
  },
  backHomeBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 13,
    fontWeight: '700',
  },

  /* Temporary Password & Credential Copy Styles */
  tempPasswordCard: {
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.primaryContainer + '40',
    borderRadius: tokens.borderRadius.card,
    padding: tokens.spacing.sm + 4,
    marginBottom: tokens.spacing.sm,
    gap: 6,
  },
  tempPasswordHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tempPasswordLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  tempPasswordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.background,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    borderRadius: tokens.borderRadius.input,
    paddingHorizontal: tokens.spacing.sm + 2,
    paddingVertical: 8,
    gap: 8,
  },
  tempPasswordInput: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.onBackground,
    paddingVertical: 2,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  tempPasswordActionBtn: {
    padding: 6,
    borderRadius: tokens.borderRadius.pill,
    backgroundColor: tokens.colors.surfaceCard,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tempPasswordNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    backgroundColor: tokens.colors.primaryContainer + '15',
    borderRadius: tokens.borderRadius.input,
    padding: tokens.spacing.xs + 4,
    marginTop: 2,
  },
  tempPasswordNoticeText: {
    flex: 1,
    fontSize: 11,
    color: tokens.colors.primaryContainer,
    lineHeight: 15,
    fontWeight: '500',
  },

  /* Credential Modal Dialog Styles */
  credDialogOverlay: {
    flex: 1,
    backgroundColor: tokens.colors.surfaceOverlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: tokens.spacing.lg,
  },
  credDialogCard: {
    backgroundColor: tokens.colors.background,
    borderRadius: tokens.borderRadius.card,
    width: '100%',
    maxWidth: 400,
    padding: tokens.spacing.lg,
    ...tokens.shadows.card,
  },
  credDialogHeader: {
    alignItems: 'center',
    marginBottom: tokens.spacing.md,
    gap: 6,
  },
  credDialogIconBox: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: tokens.colors.statusSuccess + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  credDialogTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: tokens.colors.onBackground,
  },
  credDialogSub: {
    fontSize: 12,
    color: tokens.colors.secondary,
    textAlign: 'center',
  },
  credFieldsBox: {
    backgroundColor: tokens.colors.surfaceCard,
    borderRadius: tokens.borderRadius.input,
    borderWidth: 1,
    borderColor: tokens.colors.borderSubtle,
    padding: tokens.spacing.md,
    gap: 10,
    marginBottom: tokens.spacing.md,
  },
  credFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  credFieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: tokens.colors.secondary,
    textTransform: 'uppercase',
  },
  credFieldValue: {
    fontSize: 13,
    fontWeight: '700',
    color: tokens.colors.onBackground,
  },
  credFieldPassword: {
    fontSize: 14,
    fontWeight: '800',
    color: tokens.colors.primaryContainer,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  credNoticeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: tokens.borderRadius.input,
    padding: tokens.spacing.sm,
    marginBottom: tokens.spacing.md,
  },
  credNoticeText: {
    flex: 1,
    fontSize: 11,
    color: '#92400E',
    fontWeight: '500',
    lineHeight: 15,
  },
  credCopyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.primaryContainer,
    borderRadius: tokens.borderRadius.pill,
    paddingVertical: 12,
    gap: 8,
    marginBottom: 8,
  },
  credCopyBtnText: {
    color: tokens.colors.onPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  credDoneBtn: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  credDoneBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: tokens.colors.secondary,
  },
})
